name = "Just Pause"
description = "Pauses the game if you press 'P' key. Doesn't obstruct the view with the Menu screen. Feel free to explore the crafting menu or plan your next move. It is still possible to use the regular pause method."
author = "Ksanter X"
version = "1.0"
forumthread = ""
api_version = 6
icon_atlas = "modicon.xml"
icon = "modicon.tex"
dont_starve_compatible = true
reign_of_giants_compatible = true
dst_compatible = true